name: GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # build job
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '18.x'
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install
      # Runs test
      - name: Run tests
        run: npm run test:headless
      # Runs a set of commands to build
      - name: Build
        run: npm run build:prod
      # sotre the artifact
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/pn-chat-client
          enable_jekyll: true